### ISSUE TITLE
 file open issues

### ISSUE THREAD

**Issue by markstock7** [mgcrea/node-xlsx#28]
i keep getting this warning when i try to pen xlsx file generated by node-xlsx ,
Excel could not open mySheetName (1).xlsx because some content is unreadable. Do you want to open and repair this workbook?

**Comment by fdionisi** [comment]
@markstock7 Just started implementing an example and I have the same problem.
Did you found the solution for this?

**Comment by cdtinguria** [comment]
Getting the same issue when opening a downloaded file in MS Office 2010.
Is this issue fixed? we are using v0.2.2

**Comment by cuspymd** [comment]
Could you attach a file that can not be opened?

**Comment by cdtinguria** [comment]
[MIX-Market-Report.xlsx](https://github.com/mgcrea/node-xlsx/files/756898/MIX-Market-Report.xlsx)
here it is, problem is only with MS Office 2010

**Comment by cuspymd** [comment]
The problem is caused by cells with null values in the file 'xl/worksheets/sheet1.xml'.
For example, the cell J3 is '<c r="J3"><v>null</v></c>'.
It is weird value. Blank(null) cells should not exist in this file.

Is this the file generated by node-xlsx module?
I don't think the files generated by this module can have these values

**Comment by cdtinguria** [comment]
We are generating a file to be downloaded, in case the value to be shown is empty how this can be done?

**Comment by cuspymd** [comment]
@cdtinguria You need to check the type of original data of the cell J3.
I tried to build a xlsx file with datas of null or undefined type
but its were not be saved in sheet1.xml.
