### ISSUE TITLE
why the data in xlsx is Integer,but throuth the xlsx.parse,the data change into Float

### ISSUE THREAD

**Issue by yourenA** [mgcrea/node-xlsx#59]
In my xlsx file the data is Integer . but through the xlsx.parse method , the data change into a Float.
How can I  resolve the problem?

My node-xlsx version "node-xlsx": "^0.7.4"；
The origin data:
![image](https://cloud.githubusercontent.com/assets/20793819/23839867/e4bfa83c-07db-11e7-9b1e-f5078cf39818.png)

The code:
`const workSheetsFromFile = xlsx.parse(`${__dirname}/../../${fileurl}`);
    console.log(workSheetsFromFile[0].data);`

The xlsx.parse data:
[ [ 'T(℃)', 'R(KΩ)' ],
  [ -40, 3225.4617 ],
  [ -39, 3026.3501 ],
  [ -38, 2839.6504 ],
  [ -37, 2664.7295 ],
  [ -36, 2500.9521 ],
  [ -35, 2347.6975 ],
  [ -34, 2204.3501 ],
  [ -33, 2070.3164 ],
  [ -32, 1945.0251 ],
  [ -31, 1827.9241 ],
  [ -30, 1718.49 ],
  [ -29, 1614.1907 ] ]

**Comment by yourenA** [comment]
@mgcrea Please help me?

**Comment by reviewher** [comment]
@yourenA can you share the original XLSX or XLS file?

**Comment by yourenA** [comment]
My XLSX file like this . It has Integer and Float number.
![image](https://cloud.githubusercontent.com/assets/20793819/23840009/d5460332-07dc-11e7-9d6b-e8e08192c366.png)

**Comment by reviewher** [comment]
@yourenA the data shown in the screenshot is not the same as the file.  If you change the number format you can hide the decimal point.  Here is an example:

<img width="195" alt="screen shot 2017-03-12 at 23 07 08" src="https://cloud.githubusercontent.com/assets/24845478/23840083/aa384eb6-0778-11e7-86f4-37987cfbdcca.png">

The cell actually has the value 1.5 but i changed the format by hitting "decrease decimal" and now Excel shows "2" instead of "1.5".  That's why we need to see the original workbook.  Github lets you click and drag into the comment box to upload it.

**Comment by yourenA** [comment]
HELPFUL !!!
This is my fault .
Thank you so much!
